# fly.toml app configuration file generated for dy-wetube on 2023-07-10T23:11:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dy-wetube"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
